afet-yonetim-sistemi/ays-fe-ui-automation

CODEOWNERS

Improvements to the GitHub Community Standards.
Closes #[1]
Authorized persons in the Project were added and edited in the CODEOWNERS file.
Appropriate branch protection rule added to Github project

#1 - CODEOWNERS file edited. 

---

.gitignore
pom.xml
src/test/java/feature/AYOS_Location.feature
src/test/java/pages/AYOS_Assignments_POM.java
src/test/java/pages/Login_POM.java
src/test/java/runners/RunnerForCrossBrowserTest.java
src/test/java/runners/RunnerForParallelTest.java
src/test/java/step_definitions/Assignments_Location.java
src/test/java/step_definitions/Login.java
src/test/java/utilities/ConfigurationReader.java
src/test/java/utilities/MyMethods.java
src/test/java/xml_files/ParallelTest.xml

Login.feature daki hatalar giderildi.
AYOS_Location.feature daki hatalar giderildi.
runner classlardaki hatalar giderildi.
Configuration.properties dosyası oluşturularak credentials lar buraya alındı.
ConfigurationReader classı oluşturuldu.
xml_files daki hatalar giderildi.
MyMethods classına clickElementWithJavaScript methodu eklendi.
pom.xml dosyasına lombok dependency ve pipeline uyumu için pluginler eklendi.

AYS-69 | AYOS_Location.feature updated

---

src/test/java/pages/AYOS_Assignments_POM.java
src/test/java/step_definitions/AYOS_Assignments_Show.java
src/test/java/step_definitions/Assignments_Create.java
src/test/java/step_definitions/Assignments_Edit.java
src/test/java/step_definitions/Assignments_Filter.java

Element lokasyon hataları giderildi.
Tüm feature lardaki hatalar giderilip test doğruluğu kontrol edildi.

AYS-69 | Completed.

---

pom.xml

Java versiyonu 19 dan 17 ye ayarlandı. Değişiklik sonrası testlerin çalışırlığı kontrol edildi.

AYS-67 | The Java version has been set to 17.

---

pom.xml
src/test/java/feature/AYOSAssignments.feature
src/test/java/feature/AYOSAssignmentsDelete.feature
src/test/java/feature/AYOSAssignmentsEdit.feature
src/test/java/feature/AYOSAssignmentsFilter.feature
src/test/java/feature/AYOSAssignmentsShow.feature
src/test/java/feature/AYOSLocation.feature
src/test/java/pages/AYOSAssignmentsPOM.java
src/test/java/pages/LoginPOM.java
src/test/java/runners/RunnerForCrossBrowserTest.java
src/test/java/runners/RunnerForParallelTest.java
src/test/java/step_definitions/AYOSAssignmentsShow.java
src/test/java/step_definitions/AssignmentsCreate.java
src/test/java/step_definitions/AssignmentsDelete.java
src/test/java/step_definitions/AssignmentsEdit.java
src/test/java/step_definitions/AssignmentsFilter.java
src/test/java/step_definitions/AssignmentsLocation.java
src/test/java/step_definitions/Hooks.java
src/test/java/step_definitions/Login.java

Gereksiz stepler kaldırıldı.
Yoruma alınmış kullanılmayan kodlar silindi.
Class isimleri standartlara uygun olarak yeniden düzenlendi.

AYS-103 | The previously written tests edited.

---

pom.xml

Kütüphanelerin versiyonları güncellendi.
Kendi içinde conflict oluşturan versiyonlar düzeltildi.

AYS-88 | Framework Security completed.

---

pom.xml
src/test/java/feature/UsersCreate.feature
src/test/java/pages/AYOSUsersPOM.java
src/test/java/step_definitions/UsersCreate.java
src/test/java/utilities/MyMethods.java

"UsersCreate.feature" scenarios have been added.
A step definition class for UsersCreate scenarios has been added based on the scenarios.
Relevant locators have been added to the "AYOSUsersPOM" class.
Java Faker dependency has been added to the "pom.xml" file.
Methods have been added to the "MyMethods" class.
The functionality of all tests has been verified.

AYS-95 | New user creation scenarios have been added.

---

src/test/java/feature/UsersEdit.feature
src/test/java/feature/UsersShow.feature
src/test/java/pages/AYOSUsersPOM.java
src/test/java/step_definitions/UsersEdit.java
src/test/java/step_definitions/UsersShow.java

UsersEdit and UsersShow scenarios, step definitions classes added.

AYS-95 | UsersEdit and UsersShow scenarios added.

---

src/test/java/feature/UsersDelete.feature
src/test/java/pages/AYOSAssignmentsPOM.java
src/test/java/pages/AYOSUsersPOM.java
src/test/java/step_definitions/UsersDelete.java

UsersDelete.feature file and stepDefinitions class added.
The test's operability has been checked.

AYS-95 | UsersDelete.feature file added.

---

src/test/java/step_definitions/Login.java

Konfigürasyon parametrelerinin isimlendirmesi standartlara uygun olarak düzenlendi.

AYS-64 | Credentials name has been changed.

---

src/test/java/feature/AYOSAssignmentsDelete.feature
src/test/java/utilities/DriverClass.java

DriverClass'ta `--headles=new` argümanı `--headless` olarak güncellendi,
`--no-sandbox` ile `--disable-dev-shm-usage` argümanları eklendi.

AYS-64 | The missing driver option added.

---

src/test/java/feature/Logout.feature
src/test/java/pages/LogoutPOM.java
src/test/java/step_definitions/Logout.java

Provide a brief description of the changes in this pull request.
Closes #[Issue Number]
List the changes you made in this pull request.

AYS-120 | Logout function added

---

src/test/java/org/ays/browser/AysBrowser.java
src/test/java/org/ays/pages/AssignmentsPOM.java

commonBrowserArguments list and **filter** locator changed
Closes #[AYS-164]
[AYS-164]: https://afetyonetimsistemi.atlassian.net/browse/AYS-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AYS-164 | commonBrowserArguments list and filter locator changed

---

src/test/java/org/ays/feature/AssignmentsEdit.feature
src/test/java/org/ays/feature/UsersDelete.feature
src/test/java/org/ays/feature/UsersEdit.feature
src/test/java/org/ays/pages/AssignmentsPOM.java
src/test/java/org/ays/pages/UsersPOM.java
src/test/java/org/ays/step_definitions/UsersDelete.java
src/test/java/org/ays/step_definitions/UsersEdit.java

UsersDelete, UsersEdit, AssignmentEdit testleri düzenlendi.

AYS-166 | Ignored tests edited

---

src/test/java/org/ays/feature/Logout.feature
src/test/java/org/ays/step_definitions/Logout.java

Provide a brief description of the changes in this pull request.
Closes #[Issue Number]
List the changes you made in this pull request.

AYS-187| Logout Function refactored

---

src/test/java/org/ays/browser/AysPageActions.java
src/test/java/org/ays/feature/UsersCreate.feature
src/test/java/org/ays/feature/UsersDelete.feature
src/test/java/org/ays/feature/UsersEdit.feature
src/test/java/org/ays/pages/UsersPOM.java
src/test/java/org/ays/step_definitions/UsersDelete.java
src/test/java/org/ays/step_definitions/UsersEdit.java

UsersCreate Test Cases Have Been fixed.

AYS-206 | Fixing ignored tests.

---

src/test/java/org/ays/feature/UsersCreate.feature
src/test/java/org/ays/feature/UsersDelete.feature
src/test/java/org/ays/pages/UsersPOM.java
src/test/java/org/ays/step_definitions/UsersCreate.java
src/test/java/org/ays/step_definitions/UsersDelete.java

UsersCreate ve UsersDelete testleri yeni düzenlemeyle gelen pop up' a göre yeniden düzenlendi.

AYS-218 | Arranging tests according to popup

---

CODEOWNERS
CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md

…ited.
Documents have been edited.
Closes #[AYS-521]
Pull Request Template and CONTRIBUTING.md file have been edited.
[AYS-521]: https://afetyonetimsistemi.atlassian.net/browse/AYS-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AYS-521 | Documents Editing

---

src/test/java/org/ays/browser/AysPageActions.java
src/test/java/org/ays/feature/Logout.feature
src/test/java/org/ays/pages/LogoutPage.java
src/test/java/org/ays/step_definitions/Logout.java
src/test/java/org/ays/utilities/AysLocaleStorageUtil.java

Logout tests refactored.
-Updated failed tests
-Added new scenarios
None
**Reviewer Instructions:**
None
Before submitting your pull request, ensure the following:
- The pull request title follows the
standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-fe-ui-automation/blob/main/CONTRIBUTING.md#pull-request-naming-conventions)
.
- The branch name follows one of the conventions outlined in
the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-fe-ui-automation/blob/main/CONTRIBUTING.md#branch-naming-conventions)
.
- I have added positive and negative test scenarios (if applicable)
- All tests are passing.
- I tagged all test as smoke or regression
- I added newly added …

AYS-449 | Refactored logout test

---

src/test/java/org/ays/enums/AysEndpoints.java
src/test/java/org/ays/feature/AdminRegistrationPreApplicationCreation.feature
src/test/java/org/ays/feature/Login.feature
src/test/java/org/ays/feature/Logout.feature
src/test/java/org/ays/feature/UnauthorizedAccess.feature
src/test/java/org/ays/pages/AdminRegistrationApplicationDetailPage.java
src/test/java/org/ays/pages/AdminRegistrationApplicationsPage.java
src/test/java/org/ays/pages/AdminRegistrationPreApplicationPage.java
src/test/java/org/ays/pages/BasePage.java
src/test/java/org/ays/pages/LoginPage.java
src/test/java/org/ays/pages/NotFoundPage.java
src/test/java/org/ays/runners/RunnerForRegressionTest.java
src/test/java/org/ays/runners/RunnerForSmokeTest.java
src/test/java/org/ays/step_definitions/AdminRegistrationPreApplicationCreation.java
src/test/java/org/ays/step_definitions/Login.java
src/test/java/org/ays/utilities/AysRandomUtil.java
src/test/resources/ays_ui_elements_en.properties
src/test/resources/ays_ui_elements_tr.properties

Admin registration pre-application creation tests added
Admin registration pre-application creation tests added
Language-related test scenarios will be added later.
**Reviewer Instructions:**
None
Before submitting your pull request, ensure the following:
- The pull request title follows the
standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-fe-ui-automation/blob/main/CONTRIBUTING.md#pull-request-naming-conventions)
.
- The branch name follows one of the conventions outlined in
the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-fe-ui-automation/blob/main/CONTRIBUTING.md#branch-naming-conventions)
.
- I have added positive and negative test scenarios (if applicable) …

AYS-677 | Admin registration pre application creation

---

.github/workflows/pull-request-checker.yml

Update PR Checker to Prevent Extra Triggers in GitHub Workflow
Updated PR Checker yaml file to Prevent Extra Triggers in GitHub Workflow
**Reviewer Instructions:**
Before submitting your pull request, ensure the following:
- The pull request title follows the
standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-fe-ui-automation/blob/main/CONTRIBUTING.md#pull-request-naming-conventions)
.
- The branch name follows one of the conventions outlined in
the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-fe-ui-automat …

AYS-793 | Update PR Checker to Prevent Extra Triggers in GitHub Workflow

---

CODE_OF_CONDUCT.md
LICENSE.md
SECURITY.md

Updated License, code of conduct and security documentations with New Domain
Updated License, code of conduct and security documentations with New Domain
**Reviewer Instructions:**
Before submitting your pull request, ensure the following:
- The pull request title follows the
standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-fe-ui-automation/blob/main/CONTRIBUTING.md#pull-request-naming-conventions)
.
- The branch name follows one of the conventions outlined in
the [Branch Naming …

AYS-784 | Update License Documentation with New Domain
